version: "3.9"

services:
  nginx:
    image: my-nginx:1.0
    container_name: my-nginx
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./site-content:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network

networks:
  my-network:
