version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3303:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      springboot-mysql-net:

  alpine-jdk:
    build:
      dockerfile: alpine-jdk/Dockerfile
    image: my-alpine-jdk:1.0

  springboot-restful-webservices:
    container_name: springboot
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - alpine-jdk
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:

